pipeline {
  agent {
    docker {
      image 'maven:3.9-eclipse-temurin-17'        // pin version
      args '--network devops-net -v /var/maven/repo:/root/.m2/repository'
      reuseNode true                              // keeps workspace/cache
    }
  }

  environment {
    SONAR_HOST_URL = 'http://sonarqube:9000'     // plain env var is fine
    SONAR_TOKEN    = credentials('sonar-token')  // Secret text credential
    MAVEN_OPTS     = '-Xmx1024m'
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build & Test') {
      steps {
        sh 'mvn -B -DskipTests=false clean verify'
      }
      post {
        always { junit '**/target/surefire-reports/*.xml' }
      }
    }

    stage('SonarQube Analysis') {
      steps {
        sh '''
          mvn -B sonar:sonar \
            -Dsonar.projectKey=hello-sonar-jenkins \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.login=${SONAR_TOKEN}
        '''
      }
    }
  }
}
